tokenizer:
  tokenizer_path: "bert-base-uncased"
  max_length: 512

model:
  hidden_size: 768
  num_heads: 8
  num_blocks: 3
  hidden_dropout_prob: 0.1

trainer:
  seed: 0
  with_cuda: True
  cuda_device_id: 1
  batch_size: 128
  learning_rate: 2e-5
  epochs: 100
  num_classes: 4
  save_path: